#ifndef EXCEPTIONS_H
#define EXCEPTIONS_H

#define ADDR_SIZE_FAULT 0x00
#define TRANSLATION_FAULT_EL1 0x05
#define TRANSLATION_FAULT_EL2 0x06
#define TRANSLATION_FAULT_EL3 0x07
#define ACCESS_FLAG_FAULT_EL1 0x09
#define ACCESS_FLAG_FAULT_EL2 0x0a
#define ACCESS_FLAG_FAULT_EL3 0x0b
#define PERMISSION_FAULT_EL1 0x0d
#define PERMISSION_FAULT_EL2 0x0e
#define PERMISSION_FAULT_EL3 0x0f
#define SYNC_EXTERNAL_ABORT 0x10
#define SYNC_EXTERNAL_ABORT_ON_TRANSLATION_TABLE_WALK_EL1 0x15
#define SYNC_EXTERNAL_ABORT_ON_TRANSLATION_TABLE_WALK_EL2 0x16
#define SYNC_EXTERNAL_ABORT_ON_TRANSLATION_TABLE_WALK_EL3 0x17
#define SYNC_PARITY_ERR_ON_MEM_ACCESS 0x18
#define SYNC_PARITY_ERR_ON_MEM_ACCESS_ON_TRANSLATION_TABLE_WALK_EL1 0x1d
#define SYNC_PARITY_ERR_ON_MEM_ACCESS_ON_TRANSLATION_TABLE_WALK_EL2 0x1e
#define SYNC_PARITY_ERR_ON_MEM_ACCESS_ON_TRANSLATION_TABLE_WALK_EL3 0x1f
#define ALIGNMENT_FAULT 0x21
#define DEBUG_EVENT 0x22

extern int current_el(void);
extern void init_vector_table_el3(void);
extern int fault_status_code_el3(void);

void handle_execption(void);
int force_exception(void);

#endif // EXCEPTIONS_H